### ISSUE TITLE
`make pdk` failed after pulling from skywater-pdk

### ISSUE THREAD

**Issue by KorlaMarch** [efabless/caravel-lite#1]
## The issue
The `make pdk` command failed after it tried to fetch from the skywater-pdk repository. With error message 
```
cd /home/korlamarch/brown/chips/pdks/skywater-pdk && \
	git checkout master && git pull && \
	git checkout -qf db2e06709dc3d876aa6b74a5f3893fa5f1bc2a6e
error: pathspec 'master' did not match any file(s) known to git
make[1]: *** [/home/korlamarch/brown/chips/caravel_user_project/caravel/Makefile:394: skywater-pdk] Error 1
make[1]: Leaving directory '/home/korlamarch/brown/chips/caravel_user_project'
make: *** [Makefile:40: pdk] Error 2
```

## Steps to reproduce
run a `make pdk` on a clean setup.

## Fixes
I think this is because skywater-pdk no longer has the master branch in their Github. They only have `main` now. Locally, I changed the skywater-pdk target in `makefile` to
```
skywater-pdk: check-env $(PDK_ROOT)/skywater-pdk
	cd $(PDK_ROOT)/skywater-pdk && \
		git checkout main && git pull && \
		git checkout -qf $(SKYWATER_COMMIT)
```

**Comment by Manarabdelaty** [comment]
This issue was fixed on caravel's develop branch which has been merged to master. So, it should be working now.

**Comment by KorlaMarch** [comment]
Sounds good! closing the issue.
